<?php

/**
 * Implements hook_views_pre_render().
 */
function table_chart_views_pre_render(\Drupal\views\ViewExecutable $view) {
  // Get the views extenders to see if the table_chart extension exist.
  $extender = $view->display_handler->getExtenders();
  if (isset($extender['table_chart']->options['charting_library'])) {
    $charting_library = $extender['table_chart']->options['charting_library'];

    // Attached the libraries needed for that charing library.
    $view->element['#attached']['library'][] = 'table_chart/tabletochart';
    $view->element['#attached']['library'][] = 'table_chart/raphaeljs';
    $view->element['#attached']['library'][] = 'table_chart/tabletojson';
    $view->element['#attached']['library'][] = 'table_chart/' . $charting_library;

    $view->element['#attached']['drupalSettings']['table_chart']['charting_library'] = $charting_library;
  }
}

/**
 * Implements hook_preprocess_views_view_table().
 */
function table_chart_preprocess_views_view_table(&$vars) {
  if (!empty($vars['view'])) {
    $attributes = $vars['view']->display_handler->options['display_extenders']['table_chart']['attributes'];
    $attributes = table_chart_attributes_keyed_array($attributes);
    if (!empty($attributes)) {
      $vars['attributes'] = array_merge($vars['attributes'], $attributes);
    }
  }
}

/**
 * Convert the attributes string into an array compatible with drupal_attributes
 *
 * @param string $attributes
 *  String settings for the attributes
 * @return array
 *  Returns the array of valid attributes.
 */
function table_chart_attributes_keyed_array($attributes) {
  $tmp = explode("\n", $attributes);
  $tmp = array_filter($tmp, 'trim');

  $keyed_attributes = [];
  foreach ($tmp as $attribute) {
    parse_str($attribute, $array);
    if (is_array($array)) {
      foreach ($array as $key => $value) {
        $keyed_attributes['data-' . $key] = $value;
      }
    }
  }

  return $keyed_attributes;
}

/**
 * Callback function to fetch the list of charting library installed.
 */
function table_chart_current_installed_charting_library() {
  // check if current 2 libraries that are supported are installed.
  $options = ['_none' => t('None')];
  $options = array_merge($options, ['chartist' => t('Chartist'), 'morrisjs' => t('Morrisjs')]);
  return $options;
}
